apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend-feed
  name: backend-feed
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-feed
status:
  loadBalancer: {}
