apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-feed
    spec:
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
      containers:
      - image: cong551999/udagram-api-feed:v1
        name: udagram-api-feed
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2042Mi"
              cpu: "500m"
        env:
            - name: POSTGRES_HOST
              valueFrom: 
                configMapKeyRef:
                  name: env-variable
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom: 
                configMapKeyRef:
                  name: env-variable
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom: 
                configMapKeyRef:
                  name: env-variable
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom: 
                configMapKeyRef:
                  name: env-variable
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom: 
                configMapKeyRef:
                  name: env-variable
                  key: AWS_PROFILE
            - name: JWT_SECRET
              valueFrom: 
                configMapKeyRef:
                  name: env-variable
                  key: JWT_SECRET
            - name: URL
              valueFrom: 
                configMapKeyRef:
                  name: env-variable
                  key: URL
            - name: POSTGRES_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
        volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
status: {}
