apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: cong551999/reverseproxy:v1
        name: reverseproxy
        resources: {}
status: {}
